apiVersion: v1
kind: Service
metadata:
  name: mytutorapp-service
spec:
  type: NodePort
  selector:
    app: mytutorapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30008
